### ISSUE TITLE
how to define parameters.txt?

### ISSUE THREAD

**Issue by blueskypie** [PathwayAndDataAnalysis/mutex#12]
Because the readme doesn't provide an example of `parameters.txt`, I'm wondering if this is the correct way?
```
data-file = mut.mutex.tab
max-group-size = 8
search-on-signaling-network = false
```

Thanks!

**Comment by blueskypie** [comment]
Also, should it produce more gene sets in `ranked-groups.txt` than using `parameters.txt` containing `data-file = mut.mutex.tab` only? But I actually got fewer gene sets. why?

**Comment by ozgunbabur** [comment]
Yes, assuming you use the default first-level-random-iteration (that is 10000) and you don't try to estimate FDR. 

Compared to your first run (with single line parameter), this one only differs in max-group-size. Its default is 5, so you just increased it to 8. This means each gene set now can contain up to 8 member genes.

But this does not change the number of gene sets in the result file. In fact, the number of gene sets should be equal to the number of genes in your matrix in both cases because Mutex generates a gene set per gene, using each gene in turn as the seed of the group. 

If you see that changing max-group-size changes the number of gene sets in the results, please share your mut.mutex.tab file and let me investigate why that is happening.

**Comment by blueskypie** [comment]
Thanks for the quick response! Yes, they do have equal number of gene sets. Sorry for mis-reading the line numbers. However, using the attached input file, I don't know why two known gene sets were not identified.
[mut.mutex.tab.txt](https://github.com/PathwayAndDataAnalysis/mutex/files/5793934/mut.mutex.tab.txt)
![SF3B1,SRSF2,U2AF1,ZRSR2](https://user-images.githubusercontent.com/16052330/104145763-42738980-5396-11eb-9e08-87fc7abab2ae.png)
![CBL,KRAS,NRAS](https://user-images.githubusercontent.com/16052330/104145764-430c2000-5396-11eb-947b-112bb67a6254.png)

**Comment by blueskypie** [comment]
Also, I don't understand the following,
> In fact, the number of gene sets should be equal to the number of genes in your matrix

does it mean I should include more mutations in the input matrix in order to detect more groups? Currently  `mut.mutex.tab.txt`  only contain rows where the frequency > 2%

**Comment by ozgunbabur** [comment]
If you look in the result file ranked-groups.txt, you will see it contains one gene set per gene in the matrix. The first gene in each gene set is the "seed" of that gene set, and the score of the gene set is on the first column. A score with smaller value is a better score. 

Yes, when you have more genes, you will have more gene sets on this file, but the scores of the gene sets will deteriorate due to multiple testing (more genes, more random change for mutual exclusivity). For that reason, it is a good practice to filter out genes with few mutations. 

As for why Mutex do not find the above two gene sets:
- The second one does not look like mutually exclusive to me. Look at KRAS.NS. Its overlap with the other genes in the group is even more than random. Mutex methodology makes sure that each member in the group significantly contributes to the pattern. A gene set with good score will not contain insignificant members. in fact, the score of a group is determined by its least fitting member.
- The first group is not exactly in the Mutex results, but Mutex produces the group: [EZH2.patho, SF3B1.NS, U2AF1.patho, ATM.NS, SRSF2.NS, PHF6.NM, CALR.stop, FANCL|T372fs*]. This group contains 3 of the genes in the group you mentioned. Only ZRSR2 is missing, but judging from the image you pasted, this gene is the least significant member. So I wouldn't say Mutex couldn't find this group. It just finds a different version of the group. 

Technically, when the greedy search of Mutex starts from SF3B1.NS, it finds that the next best gene to expand the group is EZH2.NS. So it goes that way. It does not test every possible combination of members. Testing all combinations wouldn't be computationally feasible.

**Comment by blueskypie** [comment]
Thank you so much for the explanation and quick response! Really appreciate! Hope the algorithm can be improved further to detect more sets using, e.g. 
1. stepwise search
2. CNN. If it can be used for sequence alignment, it could be applied here as well since this is also a type of alignment.

just my quick two cents! Great tool, thanks again!
