### ISSUE TITLE
Error with Mutex (Main.java:125)

### ISSUE THREAD

**Issue by Rahel14350** [PathwayAndDataAnalysis/mutex#7]
Dear Ozgun,

I am working with Mutex to prepare the input file for PiCnIc R package. Here is the error I got, can you please help me with this issue:

```
java -jar target/mutex.jar MSS/MUTEX
Exception in thread "main" java.lang.NullPointerException
	at org.cbio.mutex.Main.main(Main.java:125)

```

here is my parameters.txt file:
```
max-group-size = 5
first-level-random-iteration = 10000
second-level-random-iteration = 100
data-file = MSS.txt
search-on-signaling-network = true

```
Many thanks in advance
Rahel

**Comment by ozgunbabur** [comment]
Hi Rahel, since you set "search-on-signaling-network = true", Mutex also
needs a network file. This should be set in the parameters file by
"network-file = path/to/file.txt". You can use the network file that is
provided in supplement of the original publication. Alternatively, you can
use Mutex without a network by "search-on-signaling-network = false".

Best,
Ozgun

**Comment by Rahel14350** [comment]
Dear Ozgun,
Many thanks for your promptr reply. I repeat it with search-on-signaling-network = false. and I have this error again. 
```
Number of genes = 0
Exception in thread "main" java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1471)
	at org.cbio.mutex.Main.search(Main.java:222)
	at org.cbio.mutex.Main.main(Main.java:147)

```
Would you please let me know if I am doing it wrong again?
Kind Regards,
Rahel

**Comment by ozgunbabur** [comment]
This is a different error. Mutex cannot read any gene alterations from your
data matrix. Is it possible that it is not formatted correctly?
